services:
  - type: web
    name: shopkz
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shopkz-db
          property: connectionString

databases:
  - name: shopkz-db
    databaseName: shopkz
    user: shopkz_user



